// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02IUHY-WZNWNlmHG6tmbAl7elz3zEl8Y',
    appId: '1:256852425175:web:54071b0e2728ffeb84f392',
    messagingSenderId: '256852425175',
    projectId: 'comments-app-34fc8',
    authDomain: 'comments-app-34fc8.firebaseapp.com',
    storageBucket: 'comments-app-34fc8.appspot.com',
    measurementId: 'G-SM6TM0JP6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1lbTOEzLTO4kWs6LPJ4P29IsaqHJKRdE',
    appId: '1:256852425175:android:1be86ea951903d3484f392',
    messagingSenderId: '256852425175',
    projectId: 'comments-app-34fc8',
    storageBucket: 'comments-app-34fc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAAZvQ7QSIf9apECNaY5JlxnQM8YuDkSg',
    appId: '1:256852425175:ios:0f39e0be1399646084f392',
    messagingSenderId: '256852425175',
    projectId: 'comments-app-34fc8',
    storageBucket: 'comments-app-34fc8.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAAZvQ7QSIf9apECNaY5JlxnQM8YuDkSg',
    appId: '1:256852425175:ios:0f39e0be1399646084f392',
    messagingSenderId: '256852425175',
    projectId: 'comments-app-34fc8',
    storageBucket: 'comments-app-34fc8.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02IUHY-WZNWNlmHG6tmbAl7elz3zEl8Y',
    appId: '1:256852425175:web:5f41b64a8f1d229284f392',
    messagingSenderId: '256852425175',
    projectId: 'comments-app-34fc8',
    authDomain: 'comments-app-34fc8.firebaseapp.com',
    storageBucket: 'comments-app-34fc8.appspot.com',
    measurementId: 'G-DYV1506M84',
  );

}